[package]
name = "survival"
version = "0.0.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", default-features = true, features = [
    "dynamic_linking",
    "file_watcher",
] }
bevy_ecs_tiled = "0.9"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
