[package]
name = "survival"
version = "0.0.0"
edition = "2024"

[features]
default = ["atlas"]
atlas = ["bevy_ecs_tilemap/atlas"]

[dependencies]
bevy = { version = "0.17", default-features = true, features = ["dynamic_linking"] }
bevy_ecs_tilemap = "0.17"
thiserror = "2"
tiled = { version = "0.14", default-features = false }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
